#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#  multirabbitmq:
#    enabled: true
#    connections:
#      connectionNameA:
#        host: localhost
#        port: 9000
#        username: kamran
#        password: kamran
#      connectionNameB:
#        host: localhost
#        port: 5672
#        username: kamran
#        password: kamran